package autoancillarieslimited.hiberate.entities;
// Generated Jul 1, 2014 11:22:27 AM by Hibernate Tools 3.6.0

import java.io.Serializable;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 * Customer generated by hbm2java
 */
public class Admin implements java.io.Serializable {

    private int id;
    private String email;
    private String firstName;
    private String lastName;
    private String passWord;
    private String address;

    public Admin() {
    }

    public Admin(int id) {
        this.id = id;
    }

    public Admin(int id, String email, String firstName, String lastName, String passWord, String address) {
        this.id = id;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.passWord = passWord;
        this.address = address;
    }

    
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPassWord() {
        return this.passWord;
    }

    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

   

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

   

    public static String parserCustomerToJson(Admin customer) {
        JSONObject jSONObject = new JSONObject();
        jSONObject.put("P0", customer.getId());
        jSONObject.put("P1", customer.getEmail());
        jSONObject.put("P2", customer.getFirstName());
        jSONObject.put("P3", customer.getLastName());
        jSONObject.put("P4", customer.getPassWord());
        jSONObject.put("P5", customer.getAddress());
        return jSONObject.toString();
    }

    public static Admin parserCustomerFromJSON(String dataJson) throws ParseException {
        Admin i = new Admin();
        JSONParser parser = new JSONParser();
        Object obj = parser.parse(dataJson);
        JSONObject jsonObject = (JSONObject) obj;
        int id = Integer.parseInt((String) jsonObject.get("P0"));
        String email = (String) jsonObject.get("P1");
        String firstName = (String) jsonObject.get("P2");
        String lastName = (String) jsonObject.get("P3");
        String passWord = (String) jsonObject.get("P4");
        String address = (String) jsonObject.get("P5");
        i.setId(id);
        i.setEmail(email);
        i.setFirstName(firstName);
        i.setLastName(lastName);
        i.setPassWord(passWord);
        i.setAddress(address);
        return i;
    }
}
