package autoancillarieslimited.hiberate.entities;
// Generated Jul 1, 2014 11:22:27 AM by Hibernate Tools 3.6.0

import java.io.Serializable;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

    private int id;
    private String email;
    private String firstName;
    private String lastName;
    private String passWord;
    private String phoneNumber;
    private Boolean gender;
    private String address;
    private String city;
    private String country;
    private int status;

    public Customer() {
    }

    public Customer(int id) {
        this.id = id;
    }

    public Customer(int id, String email, String firstName, String lastName, String passWord, String phoneNumber, Boolean gender, String address, String city, String country, int status) {
        this.id = id;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.passWord = passWord;
        this.phoneNumber = phoneNumber;
        this.gender = gender;
        this.address = address;
        this.city = city;
        this.country = country;
        this.status = status;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPassWord() {
        return this.passWord;
    }

    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Boolean getGender() {
        return this.gender;
    }

    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public static String parserCustomerToJson(Customer customer) {
        JSONObject jSONObject = new JSONObject();
        jSONObject.put("P0", customer.getId());
        jSONObject.put("P1", customer.getEmail());
        jSONObject.put("P2", customer.getFirstName());
        jSONObject.put("P3", customer.getLastName());
        jSONObject.put("P4", customer.getPassWord());
        jSONObject.put("P5", customer.getPhoneNumber());
        jSONObject.put("P6", customer.getGender());
        jSONObject.put("P7", customer.getAddress());
        jSONObject.put("P8", customer.getCity());
        jSONObject.put("P9", customer.getCountry());
        jSONObject.put("P10", customer.getStatus());
        return jSONObject.toString();
    }

    public static Customer parserCustomerFromJSON(String dataJson) throws ParseException {
        Customer i = new Customer();
        JSONParser parser = new JSONParser();
        Object obj = parser.parse(dataJson);
        JSONObject jsonObject = (JSONObject) obj;
        int id = Integer.parseInt((String) jsonObject.get("P0"));
        String email = (String) jsonObject.get("P1");
        String firstName = (String) jsonObject.get("P2");
        String lastName = (String) jsonObject.get("P3");
        String passWord = (String) jsonObject.get("P4");
        String phoneNumber = (String) jsonObject.get("P5");
        boolean gender = Boolean.valueOf((String) jsonObject.get("P6"));
        String address = (String) jsonObject.get("P7");
        String city = (String) jsonObject.get("P8");
        String country = (String) jsonObject.get("P9");
        int status = Integer.parseInt((String) jsonObject.get("P10"));
        i.setId(id);
        i.setEmail(email);
        i.setFirstName(firstName);
        i.setLastName(lastName);
        i.setPassWord(passWord);
        i.setPhoneNumber(phoneNumber);
        i.setGender(gender);
        i.setAddress(address);
        i.setCity(city);
        i.setCountry(country);
        i.setStatus(status);
        return i;
    }
}
