package autoancillarieslimited.hiberate.entities;
// Generated Jun 17, 2014 7:41:10 AM by Hibernate Tools 3.6.0


import java.io.Serializable;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int id;
     private Serializable email;
     private Serializable firstName;
     private Serializable lastName;
     private Serializable passWord;
     private Serializable phoneNumber;
     private Boolean gender;
     private Serializable address;
     private Serializable city;
     private Serializable country;

    public Customer() {
    }

	
    public Customer(int id) {
        this.id = id;
    }
    public Customer(int id, Serializable email, Serializable firstName, Serializable lastName, Serializable passWord, Serializable phoneNumber, Boolean gender, Serializable address, Serializable city, Serializable country) {
       this.id = id;
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.passWord = passWord;
       this.phoneNumber = phoneNumber;
       this.gender = gender;
       this.address = address;
       this.city = city;
       this.country = country;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(Serializable firstName) {
        this.firstName = firstName;
    }
    public Serializable getLastName() {
        return this.lastName;
    }
    
    public void setLastName(Serializable lastName) {
        this.lastName = lastName;
    }
    public Serializable getPassWord() {
        return this.passWord;
    }
    
    public void setPassWord(Serializable passWord) {
        this.passWord = passWord;
    }
    public Serializable getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(Serializable phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public Serializable getCity() {
        return this.city;
    }
    
    public void setCity(Serializable city) {
        this.city = city;
    }
    public Serializable getCountry() {
        return this.country;
    }
    
    public void setCountry(Serializable country) {
        this.country = country;
    }




}


