package autoancillarieslimited.hiberate.entities;
// Generated Jul 1, 2014 11:22:27 AM by Hibernate Tools 3.6.0

import java.io.Serializable;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

    private int id;
    private WareHouses wareHouses;
    private String email;
    private String password;
    private String name;
    private String address;
    private String phone;

    public Employee() {
    }

    public Employee(int id) {
        this.id = id;
    }

    public Employee(int id, WareHouses wareHouses, String email, String password, String name, String address, String phone) {
        this.id = id;
        this.wareHouses = wareHouses;
        this.email = email;
        this.password = password;
        this.name = name;
        this.address = address;
        this.phone = phone;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public WareHouses getWareHouses() {
        return this.wareHouses;
    }

    public void setWareHouses(WareHouses wareHouses) {
        this.wareHouses = wareHouses;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

}
