package autoancillarieslimited.hiberate.entities;
// Generated Jul 1, 2014 11:22:27 AM by Hibernate Tools 3.6.0


import java.io.Serializable;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int id;
     private WareHouses wareHouses;
     private Serializable email;
     private Serializable password;
     private Serializable name;
     private Serializable address;
     private Serializable phone;

    public Employee() {
    }

	
    public Employee(int id) {
        this.id = id;
    }
    public Employee(int id, WareHouses wareHouses, Serializable email, Serializable password, Serializable name, Serializable address, Serializable phone) {
       this.id = id;
       this.wareHouses = wareHouses;
       this.email = email;
       this.password = password;
       this.name = name;
       this.address = address;
       this.phone = phone;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public WareHouses getWareHouses() {
        return this.wareHouses;
    }
    
    public void setWareHouses(WareHouses wareHouses) {
        this.wareHouses = wareHouses;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getPassword() {
        return this.password;
    }
    
    public void setPassword(Serializable password) {
        this.password = password;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public Serializable getPhone() {
        return this.phone;
    }
    
    public void setPhone(Serializable phone) {
        this.phone = phone;
    }




}


