package autoancillarieslimited.hiberate.entities;
// Generated Jul 1, 2014 11:22:27 AM by Hibernate Tools 3.6.0

import java.io.Serializable;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

    private int id;
    private WareHouses wareHouses;
    private int wareHouses_ID;
    private String email;
    private String password;
    private String name;
    private String address;
    private String phone;
    
    public Employee() {
    }

    public Employee(int id) {
        this.id = id;
    }

    public Employee(int id, WareHouses wareHouses, String email, String password, String name, String address, String phone) {
        this.id = id;
        this.wareHouses = wareHouses;
        this.email = email;
        this.password = password;
        this.name = name;
        this.address = address;
        this.phone = phone;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public WareHouses getWareHouses() {
        return this.wareHouses;
    }

    public void setWareHouses(WareHouses wareHouses) {
        this.wareHouses = wareHouses;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public int getWareHouses_ID() {
        return wareHouses_ID;
    }

    public void setWareHouses_ID(int wareHouses_ID) {
        this.wareHouses_ID = wareHouses_ID;
    }

    public  static  String parserEmployeeToJson(Employee item) {
        JSONObject jSONObject = new JSONObject();
        jSONObject.put("P0", item.getId());
        jSONObject.put("P1", item.getWareHouses().getId());
        jSONObject.put("P2", item.getEmail());
        jSONObject.put("P3", item.getPassword());
        jSONObject.put("P4", item.getName());
        jSONObject.put("P5", item.getAddress());
        jSONObject.put("P6", item.getPhone());
        return jSONObject.toString();
    }
    
    public static Employee parserEmployee(String dataJson) {
        try {
            Employee i = new Employee();
            JSONParser parser = new JSONParser();
            Object obj = parser.parse(dataJson);
            JSONObject jsonObject = (JSONObject) obj;
            int id = Integer.parseInt((String) jsonObject.get("P0"));
            int warehouse_id = Integer.parseInt((String) jsonObject.get("P1"));
            String email = (String) jsonObject.get("P2");
            String password = (String) jsonObject.get("P3");
            String name = (String) jsonObject.get("P4");
            String address = (String) jsonObject.get("P5");
            String phone = (String) jsonObject.get("P6");
            i.setId(id);
            i.setName(name);
            i.setAddress(address);
            i.setPhone(phone);
            i.setEmail(email);
            i.setPassword(password);
            i.setWareHouses_ID(warehouse_id);
            return i;
        } catch (Exception ex) {
            return null;
        }
    }
}
