package autoancillarieslimited.hiberate.entities;
// Generated Jun 17, 2014 7:41:10 AM by Hibernate Tools 3.6.0


import java.io.Serializable;

/**
 * ImagesItem generated by hbm2java
 */
public class ImagesItem  implements java.io.Serializable {


     private int id;
     private Item item;
     private String imageLink;

    public ImagesItem() {
    }

	
    public ImagesItem(int id) {
        this.id = id;
    }
    public ImagesItem(int id, Item item, String imageLink) {
       this.id = id;
       this.item = item;
       this.imageLink = imageLink;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }




}


