package autoancillarieslimited.hiberate.entities;
// Generated Jul 8, 2014 9:56:00 PM by Hibernate Tools 3.6.0

/**
 * ItemOrder generated by hbm2java
 */
public class ItemOrder implements java.io.Serializable {

    private int id;
    private Item item;
    private PurchaseOrder purchaseOrder;
    private int quantity;

    public ItemOrder() {
    }

    public ItemOrder(int id, Item item, PurchaseOrder purchaseOrder, int quantity) {
        this.id = id;
        this.item = item;
        this.purchaseOrder = purchaseOrder;
        this.quantity = quantity;
    }

    public ItemOrder(int id) {
        this.id = id;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Item getItem() {
        return this.item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    public PurchaseOrder getPurchaseOrder() {
        return this.purchaseOrder;
    }

    public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
        this.purchaseOrder = purchaseOrder;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}
