package autoancillarieslimited.hiberate.entities;
// Generated Jul 3, 2014 11:16:52 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private int id;
     private String name;

    public Region() {
    }

	
    public Region(int id) {
        this.id = id;
    }
    public Region(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


}


