package autoancillarieslimited.hiberate.entities;
// Generated Jun 17, 2014 7:41:10 AM by Hibernate Tools 3.6.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * TypeItem generated by hbm2java
 */
public class TypeItem implements java.io.Serializable {

    private int id;
    private String nameType;
    private Set items = new HashSet(0);

    public TypeItem() {
    }

    public TypeItem(int id) {
        this.id = id;
    }

    public TypeItem(int id, String nameType, Set items) {
        this.id = id;
        this.nameType = nameType;
        this.items = items;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNameType() {
        return this.nameType;
    }

    public void setNameType(String nameType) {
        this.nameType = nameType;
    }

    public Set getItems() {
        return this.items;
    }

    public void setItems(Set items) {
        this.items = items;
    }

}
