package autoancillarieslimited.hiberate.entities;
// Generated Jul 1, 2014 11:22:27 AM by Hibernate Tools 3.6.0

import autoancillarieslimited.hiberate.dao.WareHousesDAO;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 * WareHouses generated by hbm2java
 */
public class WareHouses implements java.io.Serializable {

    private int id;
    private String name;
    private String address;
    private int region_ID;
    private String phone;
    private String email;
    private Set employees = new HashSet(0);
    private Region region;
    
    public WareHouses() {
    }

    public WareHouses(int id) {
        this.id = id;
    }

    public WareHouses(int id, String name, String address, int region_ID, String phone, String email) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.region_ID = region_ID;
        this.phone = phone;
        this.email = email;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set getEmployees() {
        return this.employees;
    }

    public void setEmployees(Set employees) {
        this.employees = employees;
    }

    public int getRegion_ID() {
        return region_ID;
    }

    public void setRegion_ID(int region_ID) {
        this.region_ID = region_ID;
    }

    public Region getRegion() {
        return WareHousesDAO.getInstance().getRegionByID(region_ID);
    }
    
    
    public static WareHouses parserWarehouses(String dataJson) {
        try {
            WareHouses i = new WareHouses();
            JSONParser parser = new JSONParser();
            Object obj = parser.parse(dataJson);
            JSONObject jsonObject = (JSONObject) obj;
            int id = Integer.parseInt((String) jsonObject.get("P0"));
            String name = (String) jsonObject.get("P1");
            String address = (String) jsonObject.get("P2");
            String phone = (String) jsonObject.get("P3");
            String email = (String) jsonObject.get("P4");
            int region_ID = Integer.parseInt((String) jsonObject.get("P5"));
            i.setId(id);
            i.setName(name);
            i.setAddress(address);
            i.setPhone(phone);
            i.setEmail(email);
            i.setRegion_ID(region_ID);
            return i;
        } catch (Exception ex) {
            return null;
        }
    }
    
    public  static  String parserWarehouseToJson(WareHouses item) {
        JSONObject jSONObject = new JSONObject();
        jSONObject.put("P0", item.getId());
        jSONObject.put("P1", item.getName());
        jSONObject.put("P2", item.getAddress());
        jSONObject.put("P3", item.getPhone());
        jSONObject.put("P4", item.getEmail());
        jSONObject.put("P6", item.getRegion_ID());
        return jSONObject.toString();
    }

}
