package autoancillarieslimited.hiberate.entities;
// Generated Jul 1, 2014 11:22:27 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * WareHouses generated by hbm2java
 */
public class WareHouses  implements java.io.Serializable {


     private int id;
     private String name;
     private String address;
     private String phone;
     private String email;
     private Set employees = new HashSet(0);

    public WareHouses() {
    }

	
    public WareHouses(int id) {
        this.id = id;
    }
    public WareHouses(int id, String name, String address, String phone, String email, Set employees) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.employees = employees;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


