package hiberate.model;
// Generated Jun 10, 2014 11:08:19 AM by Hibernate Tools 3.6.0


import java.io.Serializable;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int id;
     private String email;
     private String firstName;
     private String lastName;
     private String passWord;
     private String phoneNumber;
     private Boolean gender;
     private String address;
     private String city;
     private String country;

    public Customer() {
    }

	
    public Customer(int id) {
        this.id = id;
    }
    public Customer(int id, String email, String firstName, String lastName, String passWord, String phoneNumber, Boolean gender, String address, String city, String country) {
       this.id = id;
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.passWord = passWord;
       this.phoneNumber = phoneNumber;
       this.gender = gender;
       this.address = address;
       this.city = city;
       this.country = country;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassWord() {
        return this.passWord;
    }
    
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


